runtime: go
api_version: go1
service: default

instance_class: F4_1G

handlers:
# Warmup, pubsub handlers, etc.
- url: /_ah/.*
  script: _go_app
  secure: always
  login: admin

# For static resources such as css and js files.
- url: /static
  secure: always
  static_dir: static

# For admin resources.
- url: /admin/.*
  script: _go_app
  secure: always
  login: admin

# All internal handlers, such as cron.
- url: /internal/.*
  script: _go_app
  secure: always
  login: admin

# Everything goes here.
- url: /.*
  script: _go_app
  secure: always

includes:
- ./static/include.yaml

inbound_services:
- warmup
