# Copyright 2015 The LUCI Authors. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

runtime: go
api_version: 1
vm: true

beta_settings:
  service_account_scopes: "https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/devstorage.full_control,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/bigtable.data"

handlers:
- url: /s
  static_dir: static/dist
  secure: always
  #login: required

- url: /.*
  script: _go_app
  secure: always
