application: luci-milo
version: go
runtime: go
api_version: go1

handlers:
# For sideloading data for testing and development.
- url: /_ah/remote_api
  script: _go_app

# Everything goes here.
- url: /.*
  script: _go_app
  secure: always

# For Cloud Endpoints support.
- url: /_ah/spi/.*
  script: _go_app
