application: luci-milo
version: go
runtime: go
api_version: go1

handlers:
# For static resources such as css and js files.
- url: /static
  secure: always
  static_dir: static

# Everything goes here.
- url: /.*
  script: _go_app
  secure: always

# For Cloud Endpoints support.
- url: /_ah/spi/.*
  script: _go_app
