application: luci-milo
version: go
runtime: go
api_version: go1

handlers:
# For static resources such as css and js files.
- url: /static
  secure: always
  static_dir: static

# For sideloading data for testing and development.
- url: /_ah/remote_api
  script: _go_app

# Everything goes here.
- url: /.*
  script: _go_app
  secure: always

# For Cloud Endpoints support.
- url: /_ah/spi/.*
  script: _go_app

includes:
  - includes/static
builtins:
- remote_api: on
