module: default
runtime: go
api_version: go1

instance_class: F4

handlers:
- url: /_ah/start
  script: _go_app
  secure: always
  login: admin

- url: /_ah/warmup
  script: _go_app
  secure: always
  login: admin

- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- warmup
