application: luci-token-server-dev
version: 1
module: default
runtime: go
api_version: go1

instance_class: F4

automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- warmup
