module: default
runtime: go
vm: true
api_version: go1

handlers:
- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /static/(.+)\.(css|gif|ico|js|ttf|svg)
  static_files: static/\1.\2
  upload: static/(.+)\.(css|gif|ico|js|ttf|svg)
  secure: always

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- warmup
