application: luci-cron
version: 1
module: default
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /static/(.+)\.(css|gif|ico|js|ttf|svg)
  static_files: static/\1.\2
  upload: static/(.+)\.(css|gif|ico|js|ttf|svg)
  secure: always

- url: /.*
  script: _go_app
  secure: always

inbound_services:
- warmup
