application: luci-cron
version: 1
module: default
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: 1

handlers:
- url: /internal.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

includes:
  - includes/static

inbound_services:
- warmup
